// -----------------------------------------------------------------------------
//  Nilog.SourceGenerators — emits the higher-arity (6-8 argument) zero-array typed
//  logging overloads directly into Nilog.dll, lifting the hand-written 1-5 argument
//  ceiling. The generated overloads follow the exact same pattern as the manual
//  1-5 argument ones: a stack-only LogState<...> struct instead of a params object[],
//  nothing allocated when the level is disabled, and structured properties preserved.
//
//  File        : HighArityOverloadGenerator.cs
//  Developer   ::> Gehan Fernando
// -----------------------------------------------------------------------------
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Nilog.SourceGenerators;

/// <summary>
/// Generates strongly-typed, zero-array <c>Write*</c> / <c>Nilogger.Log</c> overloads for
/// 6, 7, and 8 arguments, extending the hand-written 1-5 argument overloads in
/// <c>Nilogger.cs</c> without changing their behaviour.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class HighArityOverloadGenerator : IIncrementalGenerator
{
    // The hand-written overloads cover 1-5 arguments; the generator picks up from 6.
    private const int FirstArity = 6;
    private const int LastArity = 8;

    private static readonly (string Method, string Level)[] NoExceptionLevels =
    {
        ("WriteTrace", "Trace"),
        ("WriteDebug", "Debug"),
        ("WriteInformation", "Information"),
        ("WriteWarning", "Warning"),
    };

    private static readonly (string Method, string Level)[] ErrorLevels =
    {
        ("WriteError", "Error"),
        ("WriteCritical", "Critical"),
    };

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // The generated overloads are a fixed, compilation-independent surface, so they
        // can be emitted once at post-initialization rather than reacting to user syntax.
        context.RegisterPostInitializationOutput(static ctx =>
            ctx.AddSource("Nilogger.HighArity.g.cs", SourceText.From(Build(), Encoding.UTF8)));
    }

    private static string Build()
    {
        var sb = new StringBuilder(16 * 1024);

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("#pragma warning disable CS1591 // generated overloads mirror the documented 1-5 arg ones");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Runtime.CompilerServices;");
        sb.AppendLine("using Microsoft.Extensions.Logging;");
        sb.AppendLine();
        sb.AppendLine("namespace Nilog;");
        sb.AppendLine();
        sb.AppendLine("public static partial class Nilogger");
        sb.AppendLine("{");

        for (int n = FirstArity; n <= LastArity; n++)
        {
            AppendLogState(sb, n);
            AppendEmit(sb, n);
            foreach ((string method, string level) in NoExceptionLevels)
            {
                AppendNoExceptionOverload(sb, n, method, level);
            }
            foreach ((string method, string level) in ErrorLevels)
            {
                AppendErrorWithExceptionOverload(sb, n, method, level);
                AppendErrorNoExceptionOverload(sb, n, method, level);
            }
            AppendStaticLogOverload(sb, n);
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    // "T0, T1, ..., T{n-1}"
    private static string TypeParams(int n) => string.Join(", ", Enumerable(n, i => "T" + i));

    // "T0 arg0, T1 arg1, ..." for public-facing parameter lists.
    private static string ArgParams(int n) => string.Join(", ", Enumerable(n, i => $"T{i} arg{i}"));

    // "arg0, arg1, ..."
    private static string ArgNames(int n) => string.Join(", ", Enumerable(n, i => "arg" + i));

    private static IEnumerable<string> Enumerable(int n, System.Func<int, string> f)
    {
        for (int i = 0; i < n; i++)
        {
            yield return f(i);
        }
    }

    private const string Inline =
        "    [MethodImpl(MethodImplOptions.AggressiveInlining | MethodImplOptions.AggressiveOptimization)]";

    private static void AppendLogState(StringBuilder sb, int n)
    {
        string tps = TypeParams(n);
        sb.AppendLine($"    private readonly struct LogState<{tps}> : IReadOnlyList<KeyValuePair<string, object>>");
        sb.AppendLine("    {");
        sb.AppendLine("        private readonly TemplateFormatter _fmt;");
        for (int i = 0; i < n; i++)
        {
            sb.AppendLine($"        private readonly T{i} _v{i};");
        }
        sb.AppendLine();
        sb.AppendLine("        [MethodImpl(MethodImplOptions.AggressiveInlining)]");
        sb.AppendLine($"        public LogState(TemplateFormatter fmt, {ArgParams(n).Replace("arg", "v")})");
        sb.AppendLine("        {");
        sb.AppendLine("            _fmt = fmt;");
        for (int i = 0; i < n; i++)
        {
            sb.AppendLine($"            _v{i} = v{i};");
        }
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine($"        public int Count => {n + 1};");
        sb.AppendLine();
        sb.AppendLine("        public KeyValuePair<string, object> this[int index] => index switch");
        sb.AppendLine("        {");
        for (int i = 0; i < n; i++)
        {
            sb.AppendLine($"            {i} => new(_fmt.GetName({i}), _v{i}!),");
        }
        sb.AppendLine($"            {n} => new(\"{{OriginalFormat}}\", _fmt.Template),");
        sb.AppendLine("            _ => throw new ArgumentOutOfRangeException(nameof(index))");
        sb.AppendLine("        };");
        sb.AppendLine();
        sb.AppendLine("        [MethodImpl(MethodImplOptions.AggressiveInlining)]");
        sb.AppendLine($"        public Enumerator GetEnumerator() => new(this);");
        sb.AppendLine();
        sb.AppendLine("        IEnumerator<KeyValuePair<string, object>> IEnumerable<KeyValuePair<string, object>>.GetEnumerator()");
        sb.AppendLine("            => GetEnumerator();");
        sb.AppendLine();
        sb.AppendLine("        IEnumerator IEnumerable.GetEnumerator() => GetEnumerator();");
        sb.AppendLine();
        // Render through the shared stack-allocated span path (TemplateFormatter.Render
        // supports up to 8 args) so the enabled path renders without allocating an object?[];
        // only format-specifier/overflow templates fall back to string.Format internally.
        string rendered = string.Join(", ", Enumerable(n, i => $"_v{i}!"));
        sb.AppendLine($"        public override string ToString() => _fmt.Render({n}, {rendered});");
        sb.AppendLine();
        sb.AppendLine("        public struct Enumerator : IEnumerator<KeyValuePair<string, object>>");
        sb.AppendLine("        {");
        sb.AppendLine($"            private readonly LogState<{tps}> _state;");
        sb.AppendLine("            private int _index;");
        sb.AppendLine();
        sb.AppendLine("            [MethodImpl(MethodImplOptions.AggressiveInlining)]");
        sb.AppendLine($"            internal Enumerator(LogState<{tps}> state)");
        sb.AppendLine("            {");
        sb.AppendLine("                _state = state;");
        sb.AppendLine("                _index = -1;");
        sb.AppendLine("            }");
        sb.AppendLine();
        sb.AppendLine("            [MethodImpl(MethodImplOptions.AggressiveInlining)]");
        sb.AppendLine("            public bool MoveNext()");
        sb.AppendLine("            {");
        sb.AppendLine("                _index++;");
        sb.AppendLine("                return _index < _state.Count;");
        sb.AppendLine("            }");
        sb.AppendLine();
        sb.AppendLine("            public readonly KeyValuePair<string, object> Current => _state[_index];");
        sb.AppendLine("            readonly object IEnumerator.Current => _state[_index];");
        sb.AppendLine();
        sb.AppendLine("            public void Reset() { _index = -1; }");
        sb.AppendLine("            public readonly void Dispose() { }");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static void AppendEmit(StringBuilder sb, int n)
    {
        string tps = TypeParams(n);
        string valParams = string.Join(", ", Enumerable(n, i => $"T{i} v{i}"));
        string valNames = string.Join(", ", Enumerable(n, i => "v" + i));
        sb.AppendLine(Inline);
        sb.AppendLine($"    private static void Emit<{tps}>(ILogger logger, LogLevel level, Exception exception, string message, {valParams})");
        sb.AppendLine("    {");
        sb.AppendLine("        TemplateFormatter fmt = GetFormatter(message ?? \"N/A\");");
        sb.AppendLine($"        logger.Log(level, GetEventId(level), new LogState<{tps}>(fmt, {valNames}), exception, static (s, _) => s.ToString());");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static void AppendNoExceptionOverload(StringBuilder sb, int n, string method, string level)
    {
        string tps = TypeParams(n);
        sb.AppendLine(Inline);
        sb.AppendLine($"    public static void {method}<{tps}>(this ILogger logger, string message, {ArgParams(n)})");
        sb.AppendLine("    {");
        sb.AppendLine("        ArgumentNullException.ThrowIfNull(logger);");
        sb.AppendLine("        ArgumentNullException.ThrowIfNull(message);");
        sb.AppendLine($"        if (!logger.IsEnabled(LogLevel.{level})) {{ return; }}");
        sb.AppendLine($"        Emit(logger, LogLevel.{level}, null!, message, {ArgNames(n)});");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static void AppendErrorWithExceptionOverload(StringBuilder sb, int n, string method, string level)
    {
        string tps = TypeParams(n);
        sb.AppendLine(Inline);
        sb.AppendLine($"    public static void {method}<{tps}>(this ILogger logger, string message, Exception exception, {ArgParams(n)})");
        sb.AppendLine("    {");
        sb.AppendLine("        ArgumentNullException.ThrowIfNull(logger);");
        sb.AppendLine("        ArgumentNullException.ThrowIfNull(message);");
        sb.AppendLine("        ArgumentNullException.ThrowIfNull(exception);");
        sb.AppendLine($"        if (!logger.IsEnabled(LogLevel.{level})) {{ return; }}");
        sb.AppendLine($"        Emit(logger, LogLevel.{level}, exception, message, {ArgNames(n)});");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static void AppendErrorNoExceptionOverload(StringBuilder sb, int n, string method, string level)
    {
        string tps = TypeParams(n);
        sb.AppendLine(Inline);
        // Matches the hand-written 1-5 arg Error/Critical no-exception overloads: priority
        // -1 keeps a leading Exception argument binding to the with-exception overload above.
        sb.AppendLine("    [OverloadResolutionPriority(-1)]");
        sb.AppendLine($"    public static void {method}<{tps}>(this ILogger logger, string message, {ArgParams(n)})");
        sb.AppendLine("    {");
        sb.AppendLine("        ArgumentNullException.ThrowIfNull(logger);");
        sb.AppendLine("        ArgumentNullException.ThrowIfNull(message);");
        sb.AppendLine($"        if (!logger.IsEnabled(LogLevel.{level})) {{ return; }}");
        sb.AppendLine($"        Emit(logger, LogLevel.{level}, null!, message, {ArgNames(n)});");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static void AppendStaticLogOverload(StringBuilder sb, int n)
    {
        string tps = TypeParams(n);
        sb.AppendLine(Inline);
        // Mirrors the hand-written Log<T0..T4>: stays at default priority so a plain typed call
        // binds here (zero array). A trailing Exception still binds to the dedicated
        // Log(..., Exception, params object[]) overload, which carries a higher priority.
        sb.AppendLine($"    public static void Log<{tps}>(ILogger logger, LogLevel level, string message, {ArgParams(n)})");
        sb.AppendLine("    {");
        sb.AppendLine("        ArgumentNullException.ThrowIfNull(logger);");
        sb.AppendLine("        if (!logger.IsEnabled(level)) { return; }");
        sb.AppendLine($"        Emit(logger, level, null!, message, {ArgNames(n)});");
        sb.AppendLine("    }");
        sb.AppendLine();
    }
}
